In [1]:
 import pandas as pd

In [20]:
nba = pd.read_csv('../nba.csv')

Broadcasting a value:

In [21]:
nba.insert(loc=5, column='AgePlusTen', value=nba['Age']+10)

In [22]:
nba.head(n=5)

,Name,Team,Number,Position,Age,AgePlusTen,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,35.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,35.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,37.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,32.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,39.0,6-10,231.0,NaN,5000000.0

Or...

In [23]:
nba.insert(loc=6, column='AgePlusTwenty', value=nba['Age'].add(20))

In [24]:
nba.head()

,Name,Team,Number,Position,Age,AgePlusTen,AgePlusTwenty,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,35.0,45.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,35.0,45.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,37.0,47.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,32.0,42.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,39.0,49.0,6-10,231.0,NaN,5000000.0